{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import napari\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import z5py\n",
    "from pathlib import Path\n",
    "import numpy as np\n",
    "\n",
    "from cryofib.n5_utils import read_volume, print_key_tree, write_volume\n",
    "from cryofib.napari_utils import napari_add_group"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## View n5 datasets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# data_dir = Path(\"/g/kreshuk/buglakova/data/cryofib/segm_fibsem/F107\")\n",
    "em_n5_path = Path(\"/scratch/buglakova/data/cryofib/segm_fibsem/F107/multicut_pipeline/F107_A1_em_pipeline.n5\")\n",
    "\n",
    "f_em = z5py.File(em_n5_path, \"r\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Key structure of z5 file /scratch/buglakova/data/cryofib/segm_fibsem/F107/multicut_pipeline/F107_A1_em_pipeline.n5\n",
      "watershed\n",
      "watershed/3D_ws\n",
      "input\n",
      "input/raw_norm\n",
      "input/fg_mask\n",
      "input/raw\n",
      "prediction\n",
      "prediction/bg\n",
      "prediction/fg\n",
      "prediction/boundaries\n",
      "prediction/extra\n",
      "multicut\n"
     ]
    }
   ],
   "source": [
    "print_key_tree(f_em)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Read volumes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'z5py.file.File'>\n",
      "Reading roi slice(None, None, None) of volume input/raw_norm from /scratch/buglakova/data/cryofib/segm_fibsem/F107/multicut_pipeline/F107_A1_em_pipeline.n5\n",
      "Read volume with shape (1350, 1506, 1647), data type float32\n"
     ]
    }
   ],
   "source": [
    "roi = np.s_[:]\n",
    "em = read_volume(f_em, \"input/raw_norm\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'z5py.file.File'>\n",
      "Reading roi slice(None, None, None) of volume prediction/boundaries from /scratch/buglakova/data/cryofib/segm_fibsem/F107/multicut_pipeline/F107_A1_em_pipeline.n5\n",
      "Read volume with shape (1350, 1506, 1647), data type float32\n"
     ]
    }
   ],
   "source": [
    "boundaries = read_volume(f_em, \"prediction/boundaries\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "# extra = read_volume(f_em, \"prediction/extra\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'z5py.file.File'>\n",
      "Reading roi slice(None, None, None) of volume multicut from /scratch/buglakova/data/cryofib/segm_fibsem/F107/multicut_pipeline/F107_A1_em_pipeline.n5\n",
      "Read volume with shape (1350, 1506, 1647), data type uint64\n"
     ]
    }
   ],
   "source": [
    "multicut = read_volume(f_em, \"multicut\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# fg_mask = read_volume(f_em, \"input/fg_mask\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# ws = read_volume(f_em, \"watershed/3D_ws\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Open raw in napari"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-buglakov'\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:decrease_brush_size), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:increase_brush_size), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:select_all_data), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:select_all_in_slice), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:show_shortcuts), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n",
      "/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:344: UserWarning: Attempting to unbind an action which does not exists (napari:toggle_preserve_labels), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.\n",
      "  action_manager.unbind_shortcut(action)\n"
     ]
    }
   ],
   "source": [
    "v = napari.Viewer()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Labels layer 'multicut' at 0x7f8e902e4e20>"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "v.add_image(em, name=\"raw\")\n",
    "v.add_image(boundaries, name=\"boundaries\")\n",
    "v.add_labels(multicut, name=\"multicut\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [],
   "source": [
    "# v.add_labels(fg_mask, name=\"fg_mask\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "# v.add_image(extra, name=\"extra\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23416 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23460 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23457 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23457 is out of bounds for axis 0 with size 23415\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23457 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23457 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23474 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23474 is out of bounds for axis 0 with size 23415\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23570 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23677 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23677 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23677 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23680 is out of bounds for axis 0 with size 23415\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23662 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23662 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23662 is out of bounds for axis 0 with size 23415\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23662 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23662 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23680 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23574 is out of bounds for axis 0 with size 23415\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/_qt/widgets/qt_dims_slider.py\", line 141, in _value_changed\n",
      "    self.dims.set_current_step(self.axis, value)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/dims.py\", line 288, in set_current_step\n",
      "    self.current_step = full_current_step\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/evented_model.py\", line 234, in __setattr__\n",
      "    getattr(self.events, name)(value=after)  # emit event\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 715, in __call__\n",
      "    self._invoke_callback(cb, event if pass_event else None)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 752, in _invoke_callback\n",
      "    _handle_exception(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/utils/events/event.py\", line 741, in _invoke_callback\n",
      "    cb()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/components/viewer_model.py\", line 318, in _update_layers\n",
      "    layer._slice_dims(\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 983, in _slice_dims\n",
      "    self._update_dims()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 669, in _update_dims\n",
      "    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 1172, in refresh\n",
      "    self.set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/base/base.py\", line 922, in set_view_slice\n",
      "    self._set_view_slice()\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 749, in _set_view_slice\n",
      "    self._load_slice(data)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 772, in _load_slice\n",
      "    self._on_data_loaded(data, sync=True)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 796, in _on_data_loaded\n",
      "    if not self._slice.on_loaded(data):\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 142, in on_loaded\n",
      "    self._set_raw_images(data.image, data.thumbnail_source)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_slice.py\", line 100, in _set_raw_images\n",
      "    self.image.raw = image\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/_image_view.py\", line 78, in raw\n",
      "    self._view = self.image_converter(raw_image)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/image/image.py\", line 1017, in _raw_to_displayed\n",
      "    return self.obj()._raw_to_displayed(*args, **kwarg)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 952, in _raw_to_displayed\n",
      "    image = self._color_lookup_func(raw_modified, self._selected_label)\n",
      "  File \"/home/buglakov/miniconda3/envs/napari_env/lib/python3.10/site-packages/napari/layers/labels/labels.py\", line 827, in _lookup_with_index\n",
      "    image = colors[im]\n",
      "IndexError: index 23568 is out of bounds for axis 0 with size 23415\n"
     ]
    }
   ],
   "source": [
    "# v.add_labels(ws, name=\"ws\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "cc1c03ff80a13df21eb451e0f9d6c275c99a059287021003aab271766020f90b"
  },
  "kernelspec": {
   "display_name": "Python [conda env:napari_env] *",
   "language": "python",
   "name": "conda-env-napari_env-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
